//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IMenuManagerInterface")]
    public interface IMenuManagerInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/GetAllMenuInfo", ReplyAction="http://tempuri.org/IMenuManagerInterface/GetAllMenuInfoResponse")]
        System.Data.DataTable GetAllMenuInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/GetAllMenuInfo", ReplyAction="http://tempuri.org/IMenuManagerInterface/GetAllMenuInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllMenuInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/GetAllMenuInfoByName", ReplyAction="http://tempuri.org/IMenuManagerInterface/GetAllMenuInfoByNameResponse")]
        System.Data.DataTable GetAllMenuInfoByName(string menuname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/GetAllMenuInfoByName", ReplyAction="http://tempuri.org/IMenuManagerInterface/GetAllMenuInfoByNameResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllMenuInfoByNameAsync(string menuname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/GetAllGroupInfo", ReplyAction="http://tempuri.org/IMenuManagerInterface/GetAllGroupInfoResponse")]
        System.Data.DataTable GetAllGroupInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/GetAllGroupInfo", ReplyAction="http://tempuri.org/IMenuManagerInterface/GetAllGroupInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllGroupInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/InsertMenuInfo", ReplyAction="http://tempuri.org/IMenuManagerInterface/InsertMenuInfoResponse")]
        bool InsertMenuInfo(string menuname, string path, int parentid, int sort, string createby, string ImagePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/InsertMenuInfo", ReplyAction="http://tempuri.org/IMenuManagerInterface/InsertMenuInfoResponse")]
        System.Threading.Tasks.Task<bool> InsertMenuInfoAsync(string menuname, string path, int parentid, int sort, string createby, string ImagePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/UpdateMenuInfo", ReplyAction="http://tempuri.org/IMenuManagerInterface/UpdateMenuInfoResponse")]
        bool UpdateMenuInfo(int menuid, string menuname, string path, int parentid, int sort, string updateby, string ImagePath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuManagerInterface/UpdateMenuInfo", ReplyAction="http://tempuri.org/IMenuManagerInterface/UpdateMenuInfoResponse")]
        System.Threading.Tasks.Task<bool> UpdateMenuInfoAsync(int menuid, string menuname, string path, int parentid, int sort, string updateby, string ImagePath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuManagerInterfaceChannel : WindowsForms.ServiceReference3.IMenuManagerInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuManagerInterfaceClient : System.ServiceModel.ClientBase<WindowsForms.ServiceReference3.IMenuManagerInterface>, WindowsForms.ServiceReference3.IMenuManagerInterface {
        
        public MenuManagerInterfaceClient() {
        }
        
        public MenuManagerInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuManagerInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuManagerInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuManagerInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllMenuInfo() {
            return base.Channel.GetAllMenuInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllMenuInfoAsync() {
            return base.Channel.GetAllMenuInfoAsync();
        }
        
        public System.Data.DataTable GetAllMenuInfoByName(string menuname) {
            return base.Channel.GetAllMenuInfoByName(menuname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllMenuInfoByNameAsync(string menuname) {
            return base.Channel.GetAllMenuInfoByNameAsync(menuname);
        }
        
        public System.Data.DataTable GetAllGroupInfo() {
            return base.Channel.GetAllGroupInfo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllGroupInfoAsync() {
            return base.Channel.GetAllGroupInfoAsync();
        }
        
        public bool InsertMenuInfo(string menuname, string path, int parentid, int sort, string createby, string ImagePath) {
            return base.Channel.InsertMenuInfo(menuname, path, parentid, sort, createby, ImagePath);
        }
        
        public System.Threading.Tasks.Task<bool> InsertMenuInfoAsync(string menuname, string path, int parentid, int sort, string createby, string ImagePath) {
            return base.Channel.InsertMenuInfoAsync(menuname, path, parentid, sort, createby, ImagePath);
        }
        
        public bool UpdateMenuInfo(int menuid, string menuname, string path, int parentid, int sort, string updateby, string ImagePath) {
            return base.Channel.UpdateMenuInfo(menuid, menuname, path, parentid, sort, updateby, ImagePath);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateMenuInfoAsync(int menuid, string menuname, string path, int parentid, int sort, string updateby, string ImagePath) {
            return base.Channel.UpdateMenuInfoAsync(menuid, menuname, path, parentid, sort, updateby, ImagePath);
        }
    }
}
