//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class menuinfo
    {
        public int menuid { get; set; }
        public string menuname { get; set; }
        public string path { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> sort { get; set; }
        public string createby { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string updateby { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    }
}
