//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WinformPlatformEntities : DbContext
    {
        public WinformPlatformEntities()
            : base("name=WinformPlatformEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<department> department { get; set; }
        public DbSet<menuinfo> menuinfo { get; set; }
        public DbSet<roleinfo> roleinfo { get; set; }
        public DbSet<sysuser> sysuser { get; set; }
        public DbSet<loginlog> loginlog { get; set; }
        public DbSet<operatelog> operatelog { get; set; }
        public DbSet<record> record { get; set; }
    }
}
