//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class operatelog
    {
        public int id { get; set; }
        public string username { get; set; }
        public string ip { get; set; }
        public string computername { get; set; }
        public string formname { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
