//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public int id { get; set; }
        public string No { get; set; }
        public string Date { get; set; }
        public string Red_01 { get; set; }
        public string Red_02 { get; set; }
        public string Red_03 { get; set; }
        public string Red_04 { get; set; }
        public string Red_05 { get; set; }
        public string Red_06 { get; set; }
        public string Blue { get; set; }
    }
}
