//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysuser
    {
        public string username { get; set; }
        public string password { get; set; }
        public string realname { get; set; }
        public string telephone { get; set; }
        public Nullable<int> deptno { get; set; }
        public Nullable<int> roleid { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public string createby { get; set; }
        public Nullable<int> status { get; set; }
        public string updateby { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
    
        public virtual department department { get; set; }
        public virtual roleinfo roleinfo { get; set; }
    }
}
