//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.IClientVersionInterface")]
    public interface IClientVersionInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientVersionInterface/ServerVersion", ReplyAction="http://tempuri.org/IClientVersionInterface/ServerVersionResponse")]
        string ServerVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClientVersionInterface/ServerVersion", ReplyAction="http://tempuri.org/IClientVersionInterface/ServerVersionResponse")]
        System.Threading.Tasks.Task<string> ServerVersionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClientVersionInterfaceChannel : WindowsForms.ServiceReference4.IClientVersionInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientVersionInterfaceClient : System.ServiceModel.ClientBase<WindowsForms.ServiceReference4.IClientVersionInterface>, WindowsForms.ServiceReference4.IClientVersionInterface {
        
        public ClientVersionInterfaceClient() {
        }
        
        public ClientVersionInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientVersionInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientVersionInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientVersionInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ServerVersion() {
            return base.Channel.ServerVersion();
        }
        
        public System.Threading.Tasks.Task<string> ServerVersionAsync() {
            return base.Channel.ServerVersionAsync();
        }
    }
}
