//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsForms.ServiceReference5 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference5.IDeptInfoManagerInterface")]
    public interface IDeptInfoManagerInterface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeptInfoManagerInterface/GetAllDeptInfo", ReplyAction="http://tempuri.org/IDeptInfoManagerInterface/GetAllDeptInfoResponse")]
        System.Data.DataTable GetAllDeptInfo(string deptname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeptInfoManagerInterface/GetAllDeptInfo", ReplyAction="http://tempuri.org/IDeptInfoManagerInterface/GetAllDeptInfoResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetAllDeptInfoAsync(string deptname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeptInfoManagerInterface/InsertDeptInfo", ReplyAction="http://tempuri.org/IDeptInfoManagerInterface/InsertDeptInfoResponse")]
        bool InsertDeptInfo(string deptname, string remark, string createby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeptInfoManagerInterface/InsertDeptInfo", ReplyAction="http://tempuri.org/IDeptInfoManagerInterface/InsertDeptInfoResponse")]
        System.Threading.Tasks.Task<bool> InsertDeptInfoAsync(string deptname, string remark, string createby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeptInfoManagerInterface/UpdateDeptInfo", ReplyAction="http://tempuri.org/IDeptInfoManagerInterface/UpdateDeptInfoResponse")]
        bool UpdateDeptInfo(int deptno, string deptname, string remark, string updateby);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeptInfoManagerInterface/UpdateDeptInfo", ReplyAction="http://tempuri.org/IDeptInfoManagerInterface/UpdateDeptInfoResponse")]
        System.Threading.Tasks.Task<bool> UpdateDeptInfoAsync(int deptno, string deptname, string remark, string updateby);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeptInfoManagerInterfaceChannel : WindowsForms.ServiceReference5.IDeptInfoManagerInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeptInfoManagerInterfaceClient : System.ServiceModel.ClientBase<WindowsForms.ServiceReference5.IDeptInfoManagerInterface>, WindowsForms.ServiceReference5.IDeptInfoManagerInterface {
        
        public DeptInfoManagerInterfaceClient() {
        }
        
        public DeptInfoManagerInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeptInfoManagerInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeptInfoManagerInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeptInfoManagerInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetAllDeptInfo(string deptname) {
            return base.Channel.GetAllDeptInfo(deptname);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetAllDeptInfoAsync(string deptname) {
            return base.Channel.GetAllDeptInfoAsync(deptname);
        }
        
        public bool InsertDeptInfo(string deptname, string remark, string createby) {
            return base.Channel.InsertDeptInfo(deptname, remark, createby);
        }
        
        public System.Threading.Tasks.Task<bool> InsertDeptInfoAsync(string deptname, string remark, string createby) {
            return base.Channel.InsertDeptInfoAsync(deptname, remark, createby);
        }
        
        public bool UpdateDeptInfo(int deptno, string deptname, string remark, string updateby) {
            return base.Channel.UpdateDeptInfo(deptno, deptname, remark, updateby);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDeptInfoAsync(int deptno, string deptname, string remark, string updateby) {
            return base.Channel.UpdateDeptInfoAsync(deptno, deptname, remark, updateby);
        }
    }
}
